# Generated by Django 4.2.11 on 2026-05-21 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.ImageField(upload_to="achievements/", verbose_name="Icon"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                        verbose_name="Rarity",
                    ),
                ),
                (
                    "condition_code",
                    models.CharField(
                        help_text="Code identifier for the achievement condition",
                        max_length=100,
                        verbose_name="Condition Code",
                    ),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(default=0, verbose_name="Bonus Points"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Earned At"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="gamification_app.achievement",
                        verbose_name="Achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "achievement"],
                        name="gamificatio_user_id_915716_idx",
                    ),
                    models.Index(
                        fields=["-earned_at"], name="gamificatio_earned__a11fbd_idx"
                    ),
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="StudentRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, verbose_name="Total Points"),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="Level")),
                (
                    "achievements_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Achievements Count"
                    ),
                ),
                (
                    "experience_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Experience Points"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Ranking",
                "verbose_name_plural": "Student Rankings",
                "ordering": ["-total_points", "-level", "-experience_points"],
                "indexes": [
                    models.Index(
                        fields=["-total_points"], name="gamificatio_total_p_6d2377_idx"
                    ),
                    models.Index(
                        fields=["-level"], name="gamificatio_level_850b1a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BonusPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="Points"),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("achievement", "Achievement"),
                            ("streak", "Study Streak"),
                            ("bonus", "Bonus Points"),
                            ("referral", "Referral"),
                        ],
                        max_length=20,
                        verbose_name="Bonus Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Earned At"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus Points",
                "verbose_name_plural": "Bonus Points",
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-earned_at"],
                        name="gamificatio_student_94d973_idx",
                    )
                ],
            },
        ),
    ]
