# Generated by Django 4.2.11 on 2026-05-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="AI-generated learning recommendations",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "average_tasks_per_day",
                    models.FloatField(
                        default=0.0, verbose_name="Average Tasks Per Day"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Learning Path",
                "verbose_name_plural": "Learning Paths",
            },
        ),
        migrations.CreateModel(
            name="ModuleStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_students_started",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Students Started"
                    ),
                ),
                (
                    "students_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Students Completed"
                    ),
                ),
                (
                    "average_completion_percent",
                    models.FloatField(
                        default=0.0, verbose_name="Average Completion (%)"
                    ),
                ),
                (
                    "average_module_score",
                    models.FloatField(default=0.0, verbose_name="Average Module Score"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Module Statistics",
                "verbose_name_plural": "Module Statistics",
            },
        ),
        migrations.CreateModel(
            name="StudentStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_tasks_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Tasks Completed"
                    ),
                ),
                (
                    "total_points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Points Earned"
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="Average Score"),
                ),
                (
                    "total_learning_hours",
                    models.FloatField(default=0.0, verbose_name="Total Learning Hours"),
                ),
                (
                    "average_attempts",
                    models.FloatField(default=0.0, verbose_name="Average Attempts"),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0.0, verbose_name="Success Rate (%)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Student Statistics",
                "verbose_name_plural": "Student Statistics",
            },
        ),
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_submissions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Submissions"
                    ),
                ),
                (
                    "successful_submissions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Successful Submissions"
                    ),
                ),
                (
                    "partial_submissions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Partial Submissions"
                    ),
                ),
                (
                    "failed_submissions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed Submissions"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0.0, verbose_name="Success Rate (%)"),
                ),
                (
                    "partial_rate",
                    models.FloatField(default=0.0, verbose_name="Partial Rate (%)"),
                ),
                (
                    "average_attempts",
                    models.FloatField(default=1.0, verbose_name="Average Attempts"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="Average Score"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Task Statistics",
                "verbose_name_plural": "Task Statistics",
            },
        ),
    ]
