# Generated by Django 4.2.11 on 2026-05-21 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course_app", "0001_initial"),
        ("analytics_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatistics",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="course_app.task",
                verbose_name="Task",
            ),
        ),
        migrations.AddField(
            model_name="studentstatistics",
            name="student",
            field=models.OneToOneField(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="modulestatistics",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="course_app.coursemodule",
                verbose_name="Module",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="current_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_learners",
                to="course_app.coursemodule",
                verbose_name="Current Module",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="student",
            field=models.OneToOneField(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_path",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
    ]
