# Generated by Django 4.2.11 on 2026-05-21 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Order Number"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Estimated Hours"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="book", max_length=50, verbose_name="Icon"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Course Module",
                "verbose_name_plural": "Course Modules",
                "ordering": ["order_number", "title"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("text_answer", "Text Answer"),
                            ("calculation", "Calculation"),
                            ("matrix", "Matrix/AHP"),
                            ("hierarchy", "Hierarchy/Diagram"),
                        ],
                        max_length=50,
                        verbose_name="Task Type",
                    ),
                ),
                (
                    "difficulty_level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Level 1 - Reproductive"),
                            (2, "Level 2 - Analytical"),
                            (3, "Level 3 - Creative"),
                        ],
                        default=1,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "condition_text",
                    models.TextField(
                        help_text="Task description in HTML format",
                        verbose_name="Task Condition",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation for correct answer",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "reference_answer",
                    models.JSONField(
                        help_text="Correct answer in JSON format",
                        verbose_name="Reference Answer",
                    ),
                ),
                (
                    "tolerance",
                    models.FloatField(
                        default=0.01,
                        help_text="Acceptable error margin for calculations",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Tolerance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="Points"),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(default=0, verbose_name="Order Number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="course_app.coursemodule",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["module", "order_number", "difficulty_level"],
            },
        ),
        migrations.CreateModel(
            name="TheoryMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="Theory content in HTML format",
                        verbose_name="HTML Content",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(default=0, verbose_name="Order Number"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="theory_materials/",
                        verbose_name="Attachment",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="Video URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_materials",
                        to="course_app.coursemodule",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theory Material",
                "verbose_name_plural": "Theory Materials",
                "ordering": ["module", "order_number", "title"],
            },
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_answer", models.JSONField(verbose_name="Submitted Answer")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("correct", "Correct"),
                            ("partial", "Partial"),
                            ("incorrect", "Incorrect"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Score",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Points Earned"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Attempts Count"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                (
                    "is_using_hint",
                    models.BooleanField(default=False, verbose_name="Is Using Hint"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="course_app.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Result",
                "verbose_name_plural": "Task Results",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Completion Percent",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(default=0, verbose_name="Total Score"),
                ),
                (
                    "theory_viewed_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Theory Viewed Percent",
                    ),
                ),
                (
                    "tasks_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tasks Completed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="course_app.coursemodule",
                        verbose_name="Module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Progress",
                "verbose_name_plural": "Module Progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coursemodule",
            index=models.Index(
                fields=["order_number"], name="course_app__order_n_1e2589_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursemodule",
            index=models.Index(
                fields=["is_active"], name="course_app__is_acti_176e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursemodule",
            index=models.Index(
                fields=["-created_at"], name="course_app__created_89f526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theorymaterial",
            index=models.Index(
                fields=["module", "order_number"], name="course_app__module__aef6a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theorymaterial",
            index=models.Index(
                fields=["is_active"], name="course_app__is_acti_9a2368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskresult",
            index=models.Index(
                fields=["student", "task"], name="course_app__student_361e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskresult",
            index=models.Index(fields=["status"], name="course_app__status_9d6ecc_idx"),
        ),
        migrations.AddIndex(
            model_name="taskresult",
            index=models.Index(
                fields=["-completed_at"], name="course_app__complet_027dfa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskresult",
            unique_together={("student", "task")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["module", "difficulty_level"],
                name="course_app__module__11b379_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type"], name="course_app__task_ty_413f28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_active"], name="course_app__is_acti_3b9593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduleprogress",
            index=models.Index(
                fields=["student", "module"], name="course_app__student_0b49b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduleprogress",
            index=models.Index(fields=["status"], name="course_app__status_98d96f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="moduleprogress",
            unique_together={("student", "module")},
        ),
    ]
