# Generated by Django 4.2.11 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text='Answer options for multiple choice, e.g. [{"key":"A","text":"..."}]',
                null=True,
                verbose_name="Options",
            ),
        ),
    ]
